# Generated by Django 3.1.6 on 2021-02-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
