# Generated by Django 3.1.6 on 2021-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_book_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
