# Generated by Django 3.1.6 on 2021-02-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
