# Generated by Django 3.1.6 on 2021-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='backend.Category'),
        ),
    ]
